name: FruitPeek
options:
  bundleIdPrefix: com.upily
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    CODE_SIGN_STYLE: Automatic
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

targets:
  FruitPeek:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    
    sources:
      - path: FruitPeek
        excludes:
          - "**/*.md"
          - "Resources/**"
          - "Info.plist"
    
    resources:
      - path: FruitPeek/Resources/Assets.xcassets
      - path: FruitPeek/Resources/yolov8n.mlpackage
        buildPhase: resources
    
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.upily.fruitpeek
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
        COREML_CODEGEN_LANGUAGE: Swift
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSCameraUsageDescription: "FruitPeek needs camera access to help you find fruits in the scavenger hunt!"
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        INFOPLIST_KEY_UIStatusBarHidden: YES
