name: FruitPeek
options:
  bundleIdPrefix: com.upily
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: NO
    INFOPLIST_FILE: FruitPeek/Info.plist
    CODE_SIGN_STYLE: Automatic
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

targets:
  FruitPeek:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    
    sources:
      - path: FruitPeek
        excludes:
          - "**/*.md"
          - "Resources/**"
    
    resources:
      - path: FruitPeek/Resources/Assets.xcassets
      - path: yolov8n.mlpackage
    
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.upily.fruitpeek
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
        COREML_CODEGEN_LANGUAGE: Swift
        
    info:
      path: FruitPeek/Info.plist
      properties:
        UILaunchScreen: {}
