name: GlitchSquad
options:
  bundleIdPrefix: com.upily
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    CODE_SIGN_STYLE: Automatic
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

targets:
  GlitchSquad:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    
    sources:
      - path: GlitchSquad
        excludes:
          - "**/*.md"
          - "Info.plist"
    
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.upily.glitchsquad
        PRODUCT_NAME: "Glitch Squad"
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
        COREML_CODEGEN_LANGUAGE: Swift
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: "Glitch Squad"
        INFOPLIST_KEY_NSCameraUsageDescription: "Glitch Squad needs camera access to help Pixel find items in the real world!"
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Glitch Squad may use the microphone for voice features."
        INFOPLIST_KEY_NSSpeechRecognitionUsageDescription: "Glitch Squad uses speech for Pixel's voice."
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        INFOPLIST_KEY_UIStatusBarHidden: YES
